name: Python application

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/ruff-action@v3
      with:
        args: "format --check ."
    - uses: astral-sh/ruff-action@v3
      with:
        args: "check ."
